---
- name: Cleanup AI service
  hosts: ai_servers
  become: yes
  tasks:
    - name: Stop AI service container
      ansible.builtin.shell: |
        docker stop ai_app || true
        docker rm ai_app || true

    - name: Remove AI service image
      ansible.builtin.shell: |
        docker rmi ai_service:latest || true

    - name: Remove project directory
      ansible.builtin.file:
        path: /opt/ai_service
        state: absent
