all:
  children:
    ai:
      hosts: "{{ lookup('file', '../terraform/tf_output.json') | from_json | json_query('ai_ip.value') }}"
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/test-svr.pem

    app:
      hosts: "{{ lookup('file', '../terraform/tf_output.json') | from_json | json_query('app_ip.value') }}"
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/test-svr.pem

    db:
      hosts: "{{ lookup('file', '../terraform/tf_output.json') | from_json | json_query('db_ip.value') }}"
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/test-svr.pem
